#!/bin/bash

ls_grammar () {
    docker run --rm -t rebase/antlr4 sh -c "cd /grammars-v4; ls -a */*.g4"
}

build_docker () {
    docker build -t rebase/antlr4 docker/antlr4
    docker build -t rebase/gradle docker/gradle
}

_sh_antlr4 () {
    docker run --rm -it rebase/antlr4 sh
}


gen_parser () {
    docker run --rm -v $2:/out -t rebase/antlr4 antlr4 -lib /grammars-v4 -o /out $1
}

pull () {
    docker pull pottava/gradle:2
}


launch_gradle () {
    docker run -t -v $PWD:/app --name gradle rebase/gradle gradle build --continuous
}


gradle () {
    docker exec -it gradle gradle $*
}
